# Generated by Django 3.1.5 on 2021-01-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210107_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='sit_name',
            field=models.TextField(default='-'),
        ),
    ]
