# Generated by Django 3.1.5 on 2021-01-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_main_sit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='sit_name',
        ),
        migrations.AddField(
            model_name='main',
            name='set_name',
            field=models.TextField(default='-'),
        ),
    ]
