# Generated by Django 3.1.5 on 2021-01-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210107_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='fb',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='main',
            name='link',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='main',
            name='pr',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='main',
            name='set_name',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='main',
            name='tell',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='main',
            name='tw',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='main',
            name='vi',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='main',
            name='yt',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
